### PR TITLE
Add Dockerfile to run Chiaki in a Container

### PR DESCRIPTION
**Pull request by Strubbl**
I use this Dockerfile to run chiaki. Pairing with the PS4 works very good. But the video stream is not displayed in the window where it shall be displayed. 
This is a graphics card issue. 

I just want to provide this Dockerfile in case somebody else wants to help to get it running in a container.

### CODE REVIEW

**Comment by Strubbl** [comment]
Currently i see the error messages when starting the container:
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

**Comment by thestr4ng3r** [comment]
Please put it in the `scripts` directory.

Also, did Alpine not work? I would prefer that since it is much lighter.

**Comment by Strubbl** [comment]
Maybe Alpine would have worked if i would have manipulated the source code with sed or the like. But that wasn't a clean solution IMO. Installaing glibc into Alpine is also not a clean solution.

**Comment by thestr4ng3r** [comment]
Chiaki should support musl by itself. Feel free to send another pr with fixes to the source itself.

**Comment by thestr4ng3r** [comment]
Alpine build is now fixed and tested in the CI: https://builds.sr.ht/~thestr4ng3r/job/95997
Please try again with it. You can use this as a reference: https://github.com/thestr4ng3r/chiaki/blob/master/.builds/alpine.yml

**Comment by Strubbl** [comment]
the alpine dockerfile still needs some polishing. i am going to work on it and push it afterwards.

**Comment by Strubbl** [comment]
The error from the [second comment](https://github.com/thestr4ng3r/chiaki/pull/50#issuecomment-539225296) is still valid with alpine as docker base image:

```
$ sudo docker run -v $HOME/chiaki:/home/ps4/.local/share/Chiaki -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY --device /dev/snd --name chiaki --rm --net host strubbl_chiaki
No protocol specified
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
```

**Comment by thestr4ng3r** [comment]
Any update? Is it ready from your side?

**Comment by Strubbl** [comment]
No more update currently. I do not know how to fix the mentioned error. So the Dockerfile is complete from my side.

**Comment by thestr4ng3r** [comment]
Yeah I have no idea how to use OpenGL in Docker either. So I'll just merge it for now. Thanks!

**Pull request merged**
