### PR TITLE
Expose videotoolbox hardware decoder

### PR DESCRIPTION
**Pull request by kevinxucs**
Expose videotoolbox hardware decoder for mac os

### CODE REVIEW

**Comment by thestr4ng3r** [comment]
Sorry for the delay, I wanted to make sure to test this on a real Mac before merging. Seems to work fine, so thanks!

**Comment by kevinxucs** [comment]
No worries, thanks!

**Comment by lowresponse** [comment]
Hi @kevinxucs @thestr4ng3r - in v1.3.0 of Chiaki i can see videotools hardware decoding has been added for Mac OS however i cannot seem to get it working. I can report this as a bug but wanted to check that i wasn't missing something obvious first that i needed to enable.

I am using one of the prebuilt installers

CleanShot 2020-11-30 at 12 03 09

Macbook Pro 2019 specs:
CleanShot 2020-11-30 at 12 03 30

**Comment by kevinxucs** [comment]
hmmm, it seems like it's no longer working for me as well (on big sur)

**Comment by lowresponse** [comment]
> hmmm, it seems like it's no longer working for me as well

@kevinxucs want me to promote it to an issue/bug ?

**Pull request merged**
