### PR TITLE
Add Nintendo Switch chiaki-lib support

### PR DESCRIPTION
**Pull request by H0neyBadger**
Hello, 
this PR contains minimal requirements for nintendo switch support. 
I wished to have a separated (dedicated) mbedtls commit, 
but I fixed issues as the raised during my test. 
At the end, that's difficult to segregate feature afterwards. 
let me know if you have any issue, improvement, or recommendation.
I will do my best to raise a new PR. 
Thank you a lot.

### CODE REVIEW

**Comment by thestr4ng3r** [comment]
Yeah I would have preferred to have this split up, but I will just merge as-is since I want to play with it myself.

A few questions though:
You use `#if defined(__SWITCH__) || defined(CHIAKI_LIB_ENABLE_MBEDTLS)` to check for mbedtls. Is there any particular reason to check for `defined(__SWITCH__)` here? Shouldn't `CHIAKI_LIB_ENABLE_MBEDTLS` be defined by default on switch from the build system?

Also, what is the purpose of the `fake_ctest.nintendo.net.py` script? I don't know if it really makes sense to have that in the repo.

**Comment by thestr4ng3r** [comment]
Thank you very much already!

**Comment by H0neyBadger** [comment]
Hello, 
Sorry for the late reply, I just opened my desktop.

Regarding I used `defined(__SWITCH__) || defined(CHIAKI_LIB_ENABLE_MBEDTLS)` to avoid asymmetric headers definition from lib to chiaki target. but since CHIAKI_LIB_ENABLE_MBEDTLS is forced from the root CMakeLists.txt there is no issue. 

Your are right about the `fake_ctest.nintendo.net.py`. I agree it's a bit out of Chiaki scope.  

do you want me to fix this in a new PR ;-) ?

thanks to you and all contributors on this project. This project is amazing.
PS4 remote play reversing into a GPL project is a big deal.

**Comment by thestr4ng3r** [comment]
Yes, feel free to make a pr for these things. Thank you!

**Pull request merged**
