### PR TITLE
Fix AppStream metadata

### PR DESCRIPTION
**Pull request by AsciiWolf**
/cc @thestr4ng3r

### CODE REVIEW

**Review by thestr4ng3r — CHANGES_REQUESTED** [review]
Please keep `com.metallic.chiaki` as discussed, unless strictly required.

**Comment by AsciiWolf** [comment]
As far as I know, it actually is required to own the domain used in rDNS (it is clearly noted somewhere in the freedesktop documentation) and it is definitely required on Flathub.

**Comment by AsciiWolf** [comment]
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-filespec

> Ownership of {vendor}.{tld} in the domain name system guarantees uniqueness of IDs.

**Comment by thestr4ng3r** [comment]
Ok, in that case, let's use `re.chiaki.Chiaki`

**Comment by AsciiWolf** [comment]
Done.

**Review by thestr4ng3r — APPROVED** [review]

**Comment by thestr4ng3r** [comment]
Thanks! And sorry for the initial confusion.

**Pull request merged**
